import { Offer } from '../entities/offer.entity';
import { BuyerRequest } from '../../buyer-requests/entities/buyer-request.entity';
import { User } from '../../users/entities/user.entity';
import { Product } from '../../products/entities/product.entity';
import { OfferStatus } from '../enums/offer-status.enum';

describe('Offer Entity', () => {
  describe('Entity Creation', () => {
    it('should create an offer with required fields', () => {
      const offer = new Offer();
      offer.buyerRequestId = 123;
      offer.sellerId = 1;
      offer.title = 'Test Offer';
      offer.description = 'Test offer description';
      offer.price = 100.5;

      expect(offer.buyerRequestId).toBe(123);
      expect(offer.sellerId).toBe(1);
      expect(offer.title).toBe('Test Offer');
      expect(offer.description).toBe('Test offer description');
      expect(offer.price).toBe(100.5);
      expect(offer.status).toBeUndefined(); // default is set by DB
    });

    it('should create an offer with price validation', () => {
      const offer = new Offer();
      offer.buyerRequestId = 123;
      offer.sellerId = 1;
      offer.title = 'Test Offer';
      offer.description = 'Test offer description';
      offer.price = -50; // Invalid in DB, but allowed in-memory

      expect(offer.price).toBeLessThan(0);
    });

    it('should create an offer without product (null product_id)', () => {
      const offer = new Offer();
      offer.buyerRequestId = 123;
      offer.sellerId = 1;
      offer.title = 'Test Offer';
      offer.description = 'Test offer description';
      offer.price = 100.5;

      expect(offer.productId).toBeUndefined();
    });
  });

  describe('Validation', () => {
    it('should have valid offer status enum values', () => {
      expect(OfferStatus.PENDING).toBe('pending');
      expect(OfferStatus.ACCEPTED).toBe('accepted');
      expect(OfferStatus.REJECTED).toBe('rejected');
    });

    it('should validate title length constraint', () => {
      const offer = new Offer();
      const longTitle = 'a'.repeat(101);
      offer.title = longTitle;

      expect(offer.title.length).toBeGreaterThan(100);
    });

    it('should validate price is numeric', () => {
      const offer = new Offer();
      offer.price = 99.99;

      expect(typeof offer.price).toBe('number');
      expect(offer.price).toBe(99.99);
    });
  });

  describe('Relationships', () => {
    it('should have relationship with BuyerRequest', () => {
      const offer = new Offer();
      const buyerRequest = new BuyerRequest();
      buyerRequest.id = 123;

      offer.buyerRequest = buyerRequest;
      offer.buyerRequestId = buyerRequest.id;

      expect(offer.buyerRequest).toBe(buyerRequest);
      expect(offer.buyerRequestId).toBe(123);
    });

    it('should have relationship with User (seller)', () => {
      const offer = new Offer();
      const seller = new User();
      seller.id = 1;

      offer.seller = seller;
      offer.sellerId = seller.id;

      expect(offer.seller).toBe(seller);
      expect(offer.sellerId).toBe(1);
    });

    it('should have optional relationship with Product', () => {
      const offer = new Offer();
      const product = new Product();
      product.id = 123;

      offer.product = product;
      offer.productId = product.id;

      expect(offer.product).toBe(product);
      expect(offer.productId).toBe(123);
    });
  });

  describe('Database Constraints', () => {
    it('should allow price < 0 in memory but would fail in DB', () => {
      const offer = new Offer();
      offer.price = -10;

      expect(offer.price).toBe(-10);
    });

    it('should have UUID primary key', () => {
      const offer = new Offer();

      expect(offer.id).toBeUndefined(); // UUID generated by DB on save
    });

    it('should enforce foreign key constraints (simulated)', () => {
      const offer = new Offer();
      offer.buyerRequestId = 999;
      offer.sellerId = 999;

      expect(offer.buyerRequestId).toBe(999);
      expect(offer.sellerId).toBe(999);
    });

    it('should allow null product_id', () => {
      const offer = new Offer();
      offer.productId = undefined;

      expect(offer.productId).toBeUndefined();
    });
  });
});
